version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A app worker --loglevel=info  # Replace with your project name

    # Other Celery configurations...

  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A app beat --loglevel=info
    depends_on:
      - web
      - redis
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db



  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: